config/routes.rb
Rails.application.routes.draw do

  resources :albums
  resources :album_stats
  resources :likes
  put '/album_stats/:id', to:'album_stats#update'
  get '/home', to:'home#index'
  get '/gallery', to:'gallery#index'
  get '/about', to:'aboutus#index'
  get '/contact', to:'contactus#index'
  get '/contactus', to:'contactus#index'
  get '/portfolio', to:'albums#index'
  get '/portfolio/show', to:'albums#show'
  get '/photo_listing', to: 'photo_listing#index'
  post '/login', to: 'login#index'
  get '/login', to: 'login#show'
  get '/login/create', to: 'login#create'
  post '/contactus', to: 'contactus#update'
  post '/contact', to: 'contactus#update'

  get 'home/index'
  get 'contactus/index'
  get 'aboutus/index'
  get 'gallery/index'
  get 'photo_listing/index'
  root :to =>  'home#index'
  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

end

app/models/album.rb
class Album < ActiveRecord::Base
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums =[]
    Aws.config[:credentials] = Aws::Credentials.new( ENV["AWS_ACCESS_KEY_ID"], ENV["AWS_SECRET_ACCESS_KEY"])
    s3 = Aws::S3::Resource.new(credentials: Aws::Credentials.new(ENV["AWS_ACCESS_KEY_ID"], ENV["AWS_SECRET_ACCESS_KEY"]),region:'us-east-1')
    obj  = s3.bucket("backdrop-studio")
    b =obj.objects(prefix: "gallery/portfolio/image")
    b.each do |o|
      begin 
        url = o.presigned_url(:get, expires_in: 3600) if(o.key.include?('.jpg')) 
        if url
          val = {}
          album_name =  o.key.split('gallery/portfolio/image')[1]
          if album_name 
            album_name = album_name.split('/')[1]
            album_name.slice!('.jpg')
            puts album_name
            stat = AlbumStat.where({:album => album_name}).first
            val['url'] = url
            if stat
              val['views'] = stat.views 
              val['likes'] = stat.likes
              val['caption'] = stat.caption 
              val['order'] = stat.order
              val['album'] = album_name
            else
              val['views'] = 0
              val['likes'] = 0 
              val['caption'] = "no name" 
              val['order'] = rand(100)
              val['album'] = album_name
            end
          end
          @albums << val
          @albums = @albums.sort_by{ |hash| hash['order'] }
        end
      rescue => ex
        puts album_name
        puts ex.message
      end 
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @allPortfolioPics = []
    Aws.config[:credentials] = Aws::Credentials.new( ENV["AWS_ACCESS_KEY_ID"], ENV["AWS_SECRET_ACCESS_KEY"])
    s3 = Aws::S3::Resource.new(credentials: Aws::Credentials.new(ENV["AWS_ACCESS_KEY_ID"], ENV["AWS_SECRET_ACCESS_KEY"]),region:'us-east-1')
    obj  = s3.bucket("backdrop-studio")
    b =obj.objects(prefix: "gallery/portfolio/image")
    b.each do |o|
      url  = o.presigned_url(:get, expires_in: 3600) if(o.key.include?('.jpg'))
      if url
        val = {}
        album_name =  o.key.split('gallery/portfolio/image')[1]
        if album_name
          album_name = album_name.split('/')[1]
          album_name.slice!('.jpg')
          stat = AlbumStat.where({:album => album_name}).first
          val['url'] = url
          if stat
            val['views'] = stat.views 
            val['likes'] = stat.likes
            val['caption'] = stat.caption 
            val['order'] = stat.order
            val['album'] = album_name
          else
            val['views'] = 0
            val['likes'] = 0 
            val['caption'] = "no name" 
            val['order'] = rand(100)
            val['album'] = album_name
          end
          @allPortfolioPics << val
          if album_name == params['album']
            @current_index = @allPortfolioPics.length-1
          end
        end
      end
    end
    @allPortfolioPics = @allPortfolioPics.sort_by{ |hash| hash['order'] }
  end 

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_album
    params['album'].slice! '.jpg'
    stat = AlbumStat.where({:album => params["album"]}).first
    if stat
      view = stat.views
      view = view +1
      stat.update_columns(views: view)
    end
    @path = params[:url] 
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def album_params
    params.require(:album).permit(:user, :password, :album, :secured, :created_date)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :album_name %><br>
    <%= f.text_field :album_name %>
  </div>
  <div class="field">
    <%= f.label :secured %><br>
    <%= f.check_box :secured %>
  </div>
  <div class="field">
    <%= f.label :created_date %><br>
    <%= f.datetime_select :created_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<head>
</head>
<body>
    <div class="fullscreen_block hided">
    <ul class="optionset" data-option-key="filter">
          <li class="selected"><a href="#filter" data-option-value="*">All Works</a></li>
          <!-- 

            <li><a data-option-value=".advertisement" href="#filter" title="View all post filed under advertisement">Advertisement</a></li>
            <li><a data-option-value=".cities" href="#filter" title="View all post filed under cities">Cities</a></li>
            <li><a data-option-value=".fashion" href="#filter" title="View all post filed under fashion">Fashion</a></li>
            <li><a data-option-value=".nature" href="#filter" title="View all post filed under nature">Nature</a></li>
            <li><a data-option-value=".portrait" href="#filter" title="View all post filed under portrait">Portrait</a></li>
            <li><a data-option-value=".stuff" href="#filter" title="View all post filed under stuff">Stuff</a></li>
--!>
        </ul>
        
        <div class="fs_blog_module image-grid">
          <% @albums.each do |album| %>
            <div class="blogpost_preview_fw element advertisement">
              <div class="fw_preview_wrapper">
                    <div class="gallery_item_wrapper">
                      <a href=<%= album_path(url: album['url'], id: 1, album: album['album']) %>>

                        <img src=<%= album['url']  %>  alt="" class="fw_featured_image" width="540">

                        <div class="gallery_fadder"></div>
                        <span class="gallery_ico"><i class="stand_icon icon-eye"></i></span>
                      </a>
                    </div>
                    <div class="grid-port-cont">
                        <h6><a href="simple_fullwidth_image_post.html"></a></h6>
                        <div class="block_likes">
                          <div class="post-views"><i class="stand_icon icon-eye"></i> <span><%= album['views'] %></span></div>                            
                            <div class="gallery_likes gallery_likes_add">
                                <i class="stand_icon icon-heart-o"></i>
                                <div id ="hidden_name" style="display: none;">
                                  <%= album['album']%>
                                </div>
                                <span><%= album['likes'] %></span>
                            </div>                      
                        </div>                            
                    </div>                                            
                </div>
            </div> 
          <% end %>
      </div>                       

  </div>

   	<div class="preloader"></div>     
    <footer class="fullwidth">
        <div class="footer_wrapper">
            <div class="copyright">Copyright &copy;Ramesh Sigamani. All Rights Reserved.</div>
            <div class="socials_wrapper">
                <ul class="socials_list">
                	<li><a class="ico_social_dribbble" target="_blank" href="http://dribbble.com/" title="Dribbble"></a></li>
                    <li><a class="ico_social_gplus" target="_blank" href="https://plus.google.com/" title="Google+"></a></li>
                    <li><a class="ico_social_vimeo" target="_blank" href="https://vimeo.com/" title="Vimeo"></a></li>
                    <li><a class="ico_social_pinterest" target="_blank" href="http://pinterest.com" title="Pinterest"></a></li>
                    <li><a class="ico_social_facebook" target="_blank" href="http://facebook.com" title="Facebook"></a></li>
                    <li><a class="ico_social_twitter" target="_blank" href="http://twitter.com" title="Twitter"></a></li>
                    <li><a class="ico_social_instagram" target="_blank" href="http://instagram.com" title="Instagram"></a></li>
            	</ul>
            </div>
            <div class="clear"></div>
        </div>
    </footer>
	<div class="content_bg"></div>

  <%= javascript_include_tag "jquery-ui.min.js" %>
  <%= javascript_include_tag "modules.js" %>
  <%= javascript_include_tag "theme.js" %>
  
  <script type="text/javascript">
jQuery(document).ready(function($){
  "use strict";
  setTimeout(function(){
    jQuery('.fullscreen_block').removeClass('hided');
  },2500);
  setTimeout("jQuery('.preloader').remove()", 2100);			
  /* like */
  jQuery(".gallery_likes").click(function(){
    var cnt = jQuery(this).find('span').text();
    cnt++;
    jQuery(this).find('span').text(cnt);
  var  alb = jQuery(this).find('#hidden_name').text();
    var url_album = '<%= album_stat_path(id:1)%>' + '?album='+alb.trim();
    jQuery.ajax({
      type: 'PUT',
      beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
      url:url_album ,
      data:{},
      success: function(){
        console.log('success');
      }

    });
  });
  /*------*/
});	
    </script>  
</body>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<head>
</head>
<body>


<div class="main_wrapper">
  <div class="content_wrapper">
    <div class="container simple-post-container">
      <div class="content_block no-sidebar row">
        <div class="fl-container ">
          <div class="row">                        
            <div class="posts-block simple-post">
              <div class="contentarea">
                <div class="row">
                  <div class="span12 module_cont module_blog module_none_padding module_blog_page">
                    <div class="prev_next_links">

                      <div class="fleft"><a href="javascript:void(0)">Previous</a></div>
                      <div class="fright"><a href="javascript:void(0)">Next</a></div>

                      <% @allPortfolioPics.each do |pic| %>
                        <link rel = "preload" as="image" href =<%= pic['url'] %> >
                      <% end %>

                      <%= content_tag :div, class: "temp_information", data: {allPics: @allPortfolioPics } do %>
                      <% end %>
                      <%= content_tag :div, class: "temp_information_index", data: {index: @current_index} do %>
                      <% end %>

                      <!-- <div class="fleft"><a href=<%= portfolio_path  %>>Back</a></div> -->
                    </div>
                    <div class="blog_post_page sp_post">
                      <div class="pf_output_container">                                                    
                        <div class="slider-wrapper theme-default ">
                          <div class="nivoSlider">                                                
                            <img src=<%= @path %> alt="" />
                          </div>
                        </div>
                      </div>                                                
                      <!-- 
                      <div class="blogpreview_top">
                        <div class="box_date">
                          <span class="box_month">Mar</span>
                          <span class="box_day">03</span>
                        </div>                                            
                        <div class="listing_meta">
                          <span>in <a href="javascript:void(0)">Portrait</a></span>
                          <span><a href="javascript:void(0)">3 comments</a></span>
                          <span class="preview_skills">Time spent: 12 hours</span><span class="preview_skills">Camera: Canon EOS 5D Mark II</span>
                        </div>                                        
                        <div class="author_ava"><img alt="" src="img/avatar/2.jpg" class="avatar" height="72" width="72" /></div>
                      </div>
                      <h3 class="blogpost_title">Simple Fullwidth Image Post</h3>

-->
                    </div><!--.blog_post_page -->
                </div><!-- .contentarea -->
              </div>
            </div>
            <div class="clear"></div>
          </div><!-- .fl-container -->
          <div class="clear"></div>
        </div>
      </div><!-- .container -->
    </div><!-- .content_wrapper -->
  </div><!-- .main_wrapper -->

      <div class="preload1-negibours" style="display: none;" >
        <img src=<%= @path %> alt="" />
      </div>
      <div class="preload2-negibours" style="display: none;" >
        <img src=<%= @path %> alt="" />
      </div>

  <div class="preloader"></div>     
  <footer class="fullwidth">
    <div class="footer_wrapper">
      <div class="copyright">Copyright &copy;Ramesh Sigamani. All Rights Reserved.</div>
      <div class="socials_wrapper">
        <ul class="socials_list">
          <li><a class="ico_social_dribbble" target="_blank" href="http://dribbble.com/" title="Dribbble"></a></li>
          <li><a class="ico_social_gplus" target="_blank" href="https://plus.google.com/" title="Google+"></a></li>
          <li><a class="ico_social_vimeo" target="_blank" href="https://vimeo.com/" title="Vimeo"></a></li>
          <li><a class="ico_social_pinterest" target="_blank" href="http://pinterest.com" title="Pinterest"></a></li>
          <li><a class="ico_social_facebook" target="_blank" href="http://facebook.com" title="Facebook"></a></li>
          <li><a class="ico_social_twitter" target="_blank" href="http://twitter.com" title="Twitter"></a></li>
          <li><a class="ico_social_instagram" target="_blank" href="http://instagram.com" title="Instagram"></a></li>
        </ul>
      </div>
      <div class="clear"></div>
    </div>
  </footer>
  <div class="content_bg"></div>

  <%= javascript_include_tag "jquery-ui.min.js" %>
  <%= javascript_include_tag "modules.js" %>
  <%= javascript_include_tag "theme.js" %>

  <script type="text/javascript">
jQuery(document).ready(function($){
  "use strict";
  setTimeout(function(){
    jQuery('.fullscreen_block').removeClass('hided');
  },2500);
  setTimeout("jQuery('.preloader').remove()", 1000);			
});	
var pics = [];
var current_index;
pics= jQuery('.temp_information').data().allpics;

current_index= jQuery('.temp_information_index').data().index;

jQuery('.fright').click(function(){
  console.log(current_index);
  //setNextUrl(current_index);
  if(current_index == pics.length -1){
    current_index = 0;
  }else{
    current_index ++;
  }
  var next_url = pics[current_index].url
    jQuery('.nivoSlider').children('img').attr('src',next_url);
});

var setNextUrl = function(curr){
  if(curr == pics.length -1){
    curr = 0;
  }else{
    curr ++;
  }
  var next_url = pics[curr].url
    jQuery('#preload1-negibours').children('img').attr('src',next_url);
}

var setPreviousUrl = function(curr){
  if(curr != 0){
    curr --;
  }else{
    curr = pics.length -1;
  }
  var next_url = pics[curr].url
    jQuery('#preload2-negibours').children('img').attr('src',next_url);
}

jQuery('.fleft').click(function(){
  console.log(current_index);
  //setPreviousUrl(current_index);
  if(current_index != 0){
    current_index --;
  }else{
    current_index = pics.length -1;
  }
  var next_url = pics[current_index].url;
  jQuery('.nivoSlider').children('img').attr('src',next_url);
});

  </script>  
</body>