config/routes.rb
Rails.application.routes.draw do

  resources :albums
  resources :album_stats
  resources :likes
  put '/album_stats/:id', to:'album_stats#update'
  get '/home', to:'home#index'
  get '/gallery', to:'gallery#index'
  get '/about', to:'aboutus#index'
  get '/contact', to:'contactus#index'
  get '/contactus', to:'contactus#index'
  get '/portfolio', to:'albums#index'
  get '/portfolio/show', to:'albums#show'
  get '/photo_listing', to: 'photo_listing#index'
  post '/login', to: 'login#index'
  get '/login', to: 'login#show'
  get '/login/create', to: 'login#create'
  post '/contactus', to: 'contactus#update'
  post '/contact', to: 'contactus#update'

  get 'home/index'
  get 'contactus/index'
  get 'aboutus/index'
  get 'gallery/index'
  get 'photo_listing/index'
  root :to =>  'home#index'
  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  def index
    @albums =[]
    filter = params[:filter]
    Aws.config[:credentials] = Aws::Credentials.new( ENV["AWS_ACCESS_KEY_ID"], ENV["AWS_SECRET_ACCESS_KEY"])
    s3 = Aws::S3::Resource.new(credentials: Aws::Credentials.new(ENV["AWS_ACCESS_KEY_ID"], ENV["AWS_SECRET_ACCESS_KEY"]),region:'us-east-1')
    obj  = s3.bucket("backdrop-studio")
    b =obj.objects(prefix: 'gallery/clients/image')

    b.each do |o| 
      url = o.presigned_url(:get, expires_in: 3600) if(o.key.include?('/1.jpg')) 
      if url 
        val = {}
        album_name = o.key.split("gallery/clients/image/")[1]
        if album_name
          album_name = album_name.split('/')[0]
          if filter
            stat1 = AlbumStat.where("album =  '#{album_name}' and  tags like '%#{filter}%' "  ).first
          else
            stat1 = AlbumStat.where(:album => album_name).first
          end 
          val['url'] = url
          if stat1
            val['views'] = stat1.views 
            val['likes'] = stat1.likes
            val['caption'] = stat1.caption 
            val['order'] = stat1.order
            val['album']=album_name
          else
            val['views'] = 0
            val['likes'] = rand(10) 
            val['caption'] = "no name" 
            val['order'] = rand(100)
            val['album']=album_name
          end
        end
        
        @albums << val if stat1
      end
    end
    @albums = @albums.sort_by{ |hash| hash['order'] }.reverse

  end
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/views/gallery/index.html.erb
  <head>
</head>
<body>
  <div class="fullscreen_block hided">
    <ul class="optionset" data-option-key="filter">
      <li class="<%='selected' unless params['filter']  %>"><a href="<%= gallery_path %>" data-option-value="*">All Works</a></li>
      <li class = "<%='selected' if  params['filter'] == 'bs' %> "><a  data-option-value=".baby shower" href="<%= gallery_path(:filter => 'bs') %>" title="View all post filed under babby shower ">Baby Shower</a></li>
      <li class = "<%='selected' if  params['filter'] == 'bd' %>"><a data-option-value=".birthday" href="<%= gallery_path(:filter => 'bd') %>" title="View all post filed under Birthday">Birthday</a></li>
      <li class = "<%='selected' if  params['filter'] == 'cc' %>"><a data-option-value=".cradleceremony" href="<%= gallery_path(:filter => 'cc') %>" title="View all post filed under Cradle Ceremony">Cradle Ceremony</a></li>
      <li class = "<%='selected' if  params['filter'] == 'gp' %>"><a data-option-value=".graduation" href="<%= gallery_path(:filter => 'gp') %>" title="View all post filed under Graduation">Graduation</a></li>
      <li><a data-option-value=".house warming" href="<%= gallery_path(:filter => 'hw') %>" title="View all post filed under House Warming">House Warming</a></li>

      <li><a data-option-value=".wedding anniversary" href="<%= gallery_path(:filter => 'wa') %>" title="View all post filed under Wedding Anniversary">Wedding Anniversary</a></li>

        </ul>
        <div class="fs_blog_module image-grid">

          <% @albums.each do |album| %>
            <%= l = album["url"].clone %> 
            <%= l.slice!('https://backdrop-studio.s3.amazonaws.com/gallery/clients/image/')%>
            <%= k = l.slice(0..(l.index('?'))-1) %>
            <%= i = k.slice(0..(k.index('/'))-1) %>

            <div class="blogpost_preview_fw element advertisement">
              <div class="fw_preview_wrapper">
                <div class="gallery_item_wrapper">
                    <a href=<%= login_path(:b =>i ) %> >
                    <!--
                    <img src= <%= asset_path 'assets/album/caption/2.jpg' %> alt="" class="fw_featured_image" width="540"> -->

                    <%= image_tag  album["url"],   alt:"", class:"fw_featured_image", width:"540", lazy:true %>
                    <!--
                    <img src= <%= album["url"]  %> alt="" class="fw_featured_image" oncontextmenu="return false;"  width="540">
                    -->
                    <div class="gallery_fadder"></div>
                    <span class="gallery_ico"><i class="stand_icon icon-eye"></i></span>
                  </a>
                </div>
                <div class="grid-port-cont">
                <h6><a href="simple_fullwidth_image_post.html"><%= album["caption"] %></a></h6>
                  <div class="block_likes">
                    <div class="post-views"><i class="stand_icon icon-eye"></i> <span><%= album["views"] %></span></div>                            
                    <div class="gallery_likes gallery_likes_add">
                      <i class="stand_icon icon-heart-o"></i>
                      <div id ="hidden_name" style="display: none;">
                        <%= album['album']%>
                      </div>
                      <span><%= album['likes'] %> </span>
                    </div>											
                  </div>                            
                </div>                                            
              </div>
              <div class="album-pseudo1"></div>
              <div class="album-pseudo2"></div>
            </div> 
          <% end %> 
        </div>                       
      </div>
   	<div class="preloader"></div>     
    <footer class="fullwidth">
        <div class="footer_wrapper">
            <div class="copyright">Copyright &copy;Ramesh Sigamani. All Rights Reserved.</div>
            <div class="socials_wrapper">
                <ul class="socials_list">
                	<li><a class="ico_social_dribbble" target="_blank" href="http://dribbble.com/" title="Dribbble"></a></li>
                    <li><a class="ico_social_gplus" target="_blank" href="https://plus.google.com/" title="Google+"></a></li>
                    <li><a class="ico_social_vimeo" target="_blank" href="https://vimeo.com/" title="Vimeo"></a></li>
                    <li><a class="ico_social_pinterest" target="_blank" href="http://pinterest.com" title="Pinterest"></a></li>
                    <li><a class="ico_social_facebook" target="_blank" href="http://facebook.com" title="Facebook"></a></li>
                    <li><a class="ico_social_twitter" target="_blank" href="http://twitter.com" title="Twitter"></a></li>
                    <li><a class="ico_social_instagram" target="_blank" href="http://instagram.com" title="Instagram"></a></li>
            	</ul>
            </div>
            <div class="clear"></div>
        </div>
    </footer>
	<div class="content_bg"></div>

  <%= javascript_include_tag "jquery-ui.min.js" %>
  <%= javascript_include_tag "jquery.lazyload.min.js" %>
  <%= javascript_include_tag "modules.js" %>
  <%= javascript_include_tag "theme.js" %>
  
  <script type="text/javascript">

jQuery(document).ready(function($){
  jQuery("img").lazyload({
    effect : "fadeIn"
  });
  "use strict";
  setTimeout(function(){
    jQuery('.fullscreen_block').removeClass('hided');
  },2500);
  setTimeout("jQuery('.preloader').remove()", 2100);			

  /* like */
  jQuery(".gallery_likes").click(function(){
    var cnt = jQuery(this).find('span').text();
    cnt++;
    jQuery(this).find('span').text(cnt);
    var alb = jQuery(this).find('#hidden_name').text();
    var url_album = '<%= album_stat_path(id:1)%>' + '?album='+alb.trim();
    jQuery.ajax({
      type: 'PUT',
      beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
      url:url_album ,
      data:{},
      success: function(){
        console.log('success');
      }
      
    });
  });
  /*------*/

});	
  </script>  
</body>