config/routes.rb
Rails.application.routes.draw do

  resources :albums
  resources :album_stats
  resources :likes
  put '/album_stats/:id', to:'album_stats#update'
  get '/home', to:'home#index'
  get '/gallery', to:'gallery#index'
  get '/about', to:'aboutus#index'
  get '/contact', to:'contactus#index'
  get '/contactus', to:'contactus#index'
  get '/portfolio', to:'albums#index'
  get '/portfolio/show', to:'albums#show'
  get '/photo_listing', to: 'photo_listing#index'
  post '/login', to: 'login#index'
  get '/login', to: 'login#show'
  get '/login/create', to: 'login#create'
  post '/contactus', to: 'contactus#update'
  post '/contact', to: 'contactus#update'

  get 'home/index'
  get 'contactus/index'
  get 'aboutus/index'
  get 'gallery/index'
  get 'photo_listing/index'
  root :to =>  'home#index'
  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

end

app/models/album_stat.rb
class AlbumStat < ActiveRecord::Base
end

app/controllers/album_stats_controller.rb
class AlbumStatsController < ApplicationController
  before_action :set_album_stat, only: [:show, :edit, :update, :destroy]

  # GET /album_stats
  # GET /album_stats.json
  def index
    @album_stats = AlbumStat.all
  end

  # GET /album_stats/1
  # GET /album_stats/1.json
  def show
  end

  # GET /album_stats/new
  def new
    @album_stat = AlbumStat.new
  end

  # GET /album_stats/1/edit
  def edit
  end

  

  # POST /album_stats
  # POST /album_stats.json
  def create
    @album_stat = AlbumStat.new(album_stat_params)

    respond_to do |format|
      if @album_stat.save
        format.html { redirect_to @album_stat, notice: 'Album stat was successfully created.' }
        format.json { render :show, status: :created, location: @album_stat }
      else
        format.html { render :new }
        format.json { render json: @album_stat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /album_stats/1
  # PATCH/PUT /album_stats/1.json
  def update
    puts 'calling update'

    stat = AlbumStat.where({:album => params[:album]}).first

    if stat
      likes= stat.likes
      likes= likes+1
      stat.update_columns(likes: likes)
    end
    puts 'update like success'
  end

  # DELETE /album_stats/1
  # DELETE /album_stats/1.json
  def destroy
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album_stat
      @album_stat = AlbumStat.find_by_album(params[:album])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_stat_params
      params[:album_stat]
    end
end

app/helpers/album_stats_helper.rb
module AlbumStatsHelper
end

app/views/album_stats/_form.html.erb
<%= form_for(@album_stat) do |f| %>
  <% if @album_stat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album_stat.errors.count, "error") %> prohibited this album_stat from being saved:</h2>

      <ul>
      <% @album_stat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/album_stats/edit.html.erb
<h1>Editing Album Stat</h1>

<%= render 'form' %>

<%= link_to 'Show', @album_stat %> |
<%= link_to 'Back', album_stats_path %>

app/views/album_stats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Album Stats</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @album_stats.each do |album_stat| %>
      <tr>
        <td><%= link_to 'Show', album_stat %></td>
        <td><%= link_to 'Edit', edit_album_stat_path(album_stat) %></td>
        <td><%= link_to 'Destroy', album_stat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album stat', new_album_stat_path %>

app/views/album_stats/new.html.erb
<h1>New Album Stat</h1>

<%= render 'form' %>

<%= link_to 'Back', album_stats_path %>

app/views/album_stats/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_album_stat_path(@album_stat) %> |
<%= link_to 'Back', album_stats_path %>