config/routes.rb
Rails.application.routes.draw do

  resources :albums
  resources :album_stats
  resources :likes
  put '/album_stats/:id', to:'album_stats#update'
  get '/home', to:'home#index'
  get '/gallery', to:'gallery#index'
  get '/about', to:'aboutus#index'
  get '/contact', to:'contactus#index'
  get '/contactus', to:'contactus#index'
  get '/portfolio', to:'albums#index'
  get '/portfolio/show', to:'albums#show'
  get '/photo_listing', to: 'photo_listing#index'
  post '/login', to: 'login#index'
  get '/login', to: 'login#show'
  get '/login/create', to: 'login#create'
  post '/contactus', to: 'contactus#update'
  post '/contact', to: 'contactus#update'

  get 'home/index'
  get 'contactus/index'
  get 'aboutus/index'
  get 'gallery/index'
  get 'photo_listing/index'
  root :to =>  'home#index'
  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

end

app/views/layouts/_footer.html.erb
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-80643904-1', 'auto');
ga('send', 'pageview');

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta name="description" content="RamSigman Photography">
    <meta name="keywords" content="Photography">
    
    <meta property="fb:admins" content="1787804621437843" /> 
    <meta property="og:url"           content="http://www.ramsigman.com" />
    <meta property="og:type"          content="website" />
    <meta property="og:title"         content="Ramesh Sigamani | Photography" />
    <meta property="og:description"   content="Photography is close to my heart as it helps me preserve time and memories, for my clients to gaze at a later time and feel the emotions rise from within that image. I truly feel delighted every single time someone trusts me with capturing their once in a life-time events." />

    <meta property="og:image" content="http://www.ramsigman.com/assets/about_us.jpg" />


    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="shortcut icon" href= <%= image_url('fav.png','v' => :'1') %>   type="image/x-icon">
    <link rel="apple-touch-icon" href= " <%= image_url('apple_icons_57x57.png') %>" >
    <link rel="apple-touch-icon" sizes="72x72" href= " <%= image_url('apple_icons_72x72.png') %>" >
    <link rel="apple-touch-icon" sizes="114x114" href="<%= image_url('apple_icons_72x72.png') %>">
    <title>Ramesh Sigamani | Photography</title>
    <link href="http://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Roboto:400,300,500,900" rel="stylesheet" type="text/css">
    <%= csrf_meta_tag %>
    <%= stylesheet_link_tag "theme.css" %>
    <%= stylesheet_link_tag "responsive.css" %>
    <%= stylesheet_link_tag "custom.css" %>

    <%= javascript_include_tag "jquery.min.js" %>
    <%= javascript_include_tag "jquery.lazyload.min.js" %>
    <%= render 'layouts/footer' %>
  </head>
  <body>

            <header class="main_header" style="<%= 'background: linear-gradient(rgba(255, 255, 255, 0.81), rgba(255, 255, 255, 0));' if current_page?(home_path) || current_page?(root_path) %>"  >

    <div class="header_wrapper">
      <div class="logo_sect">
        
        <a href=<%= home_path %>  class="logo">
          <img src="<%= image_url 'logo.png' %>" alt=""  class="logo_def">
          <img src="<%= image_url 'retina/logo.png' %>" alt="" class="logo_retina">
        </a>

        <div class="slogan">Photography</div>
      </div>
      <div class="header_rp">
        <nav>
        <div class="menu-main-menu-container">
          <ul id="menu-main-menu" class="menu">
            <li class="<%= 'current-menu-parent' if current_page?(home_path) || current_page?(root_path) %> menu-item-has-children">
            <a href= <%= home_path %>><span>Home</span></a>
            </li>
            <li class="<%= 'current-menu-parent' if current_page?(gallery_path)%> menu-item-has-children">
            <a href=<%=gallery_path %>><span>Gallery</span></a>
            </li>
            <li class="<%= 'current-menu-parent' if current_page?(portfolio_path)%> menu-item-has-children">
            <a href=<%=portfolio_path %>><span>Portfolio</span></a>
            </li>
            <li class="<%= 'current-menu-parent' if current_page?(about_path)%> menu-item-has-children">
            <a href=<%=about_path %>><span>About</span></a>
            </li>
            <li class="<%= 'current-menu-parent' if current_page?(contact_path)%> menu-item-has-children">
            <a href=<%=contact_path %>><span>Contact</span></a>
            </li>
          </ul>
        </div>
        </nav>
        <a class="search_toggler" href="#"></a>
        </div>
        <div class="clear"></div>
    </div>
    </header>


    <%= yield %>

  </body>
</html>